jasypt:
  encryptor:
    password: ${ENCRYPTOR_PASSWORD}
    algorithm: PBEWithMD5AndDes
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  #    open-in-view: false
  datasource:
    username: root
    password: ENC(ypsHAcE8q7BNlp3kq7XY8npjT563AoeM)
    url: jdbc:mysql://47.106.137.238:3306/test?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false
  redis:
    host: 47.104.181.214
    password: ENC(ypsHAcE8q7BNlp3kq7XY8npjT563AoeM)
    port: 6380
logging:
  level:
    root: info
    com:
      gargoylesoftware: off
server:
  error:
    include-message: always

#custom configurations
application:
  jwt:
    secretKey : ENC(79f/Z0XluIlmDjSEx5Gkqle5hVjB1G5XlwYpJ27DKSHcP24IcZzfJaic9zvwov4aroAZZeYNZjM=)
    authorizationHeader : "Authorization"
    tokenPrefix : "Bearer "
    tokenExpirationAfterDays : 5
  elasticsearch:
    url : "47.104.181.214:9200"
  user:
    default:
      avatar : "https://cdn.acwing.com/media/user/profile/photo/192283_md_bc37717ec6.jpg"
  oauth2:
    client:
      registrations:
        github :
          clientId: ENC(VUe9YoFK1nK1BZZq+x00lEGzftZzXL2lCBvL14CFuXM=)
          clientSecret: ENC(7S9EJjPaOXbK4pMZMih2VLgWrLk/xHfzbCeuRXWWSg14SYOdvE1jzO/kGJLmn32Y4I0ixDbhYYA=)
      jsonFields:
        github :
          username : "login"
          nickname : "name"
          avatar : "avatar_url"
          home : "html_url"
  selenium:
    enable: "false"

